Add max_instance_lifetime
banyansecurity/terraform-aws-banyan-accesstier pull request #14
Opened 2021-03-25 04:55 UTC by rb-nr

This allows auto rotation of our ASG by setting the maximum amount of time, in seconds, that an instance can be in service

2021-03-26 14:33 UTC, tradel requested changes
If the value must be 0 or between 604800 and 31536000, then why is the default null? Shouldn't it be 0?

2021-03-26 14:46 UTC, rb-nr commented
A default of `null` means that the input will not be inserted into the resource in order to keep the module backwards compatible. However, if the value is not null, it would need to be one of those numbers.

2021-03-26 14:52 UTC, tradel commented
Is there a difference in behavior between `null` and 0? If not, I think we should make the default 0, as the _behavior_ would be the same if the var isn't supplied.

2021-03-26 15:19 UTC, rb-nr commented
Not sure. I know without a doubt that if any resource argument is `null` the argument isn't provided, which is safer than guessing if `0` is the same as if the value wasn't supplied.

2021-03-26 15:43 UTC, rb-nr commented
According to [AWS: Replacing Auto Scaling instances based on maximum instance lifetime
](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html)

> When configuring the maximum instance lifetime for your Auto Scaling group, you must specify a value of at least 86,400 seconds (1 day). To clear a previously set value, specify a new value of 0.

> Note that instances are not guaranteed to be replaced only at the end of their maximum duration. In some situations, Amazon EC2 Auto Scaling might need to start replacing instances immediately after you configure the maximum instance lifetime parameter. The intention of this more aggressive behavior is to avoid replacing all instances at the same time.

So setting the `0` default could also start terminating people's instances... but could also be a reset ? Idk, still seems like `null` is safer to me as it will retain backwards compatibility without a doubt.

2021-03-27 16:20 UTC, merged

2021-03-27 16:20 UTC, tradel reviewed
OK